# Generated by Django 3.2.5 on 2021-07-07 11:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20210707_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='address',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('profile', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='profil.profilepage')),
            ],
        ),
    ]
