# Generated by Django 3.2.5 on 2021-07-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMenu',
            new_name='Menu',
        ),
    ]
