= Skill-DB Prototype
Peter Paul Kiefer
v2, 4. Juli 2021
:imagesdir: ./images
:icons: font
:toc: right
:toclevels: 3
:source-highlighter: pygments
:stem: 

This is a description of "Skill DB"; a web portal used to expose development skills to 
prospective customers. Skill DB is a real project I plan to extend and use it 
on my own and for commercial purposes. For now I've exposed it to the public domain 
as a show case and example how I would create a web portal with django and wagtail.


== Intro

=== Motivation

I'm a software engineer since 1994. For more than 25 years I worked on various kinds of projects, 
with a variety of programming languages, frameworks, development techniques and tools. I worked with
different roles like developer, tester, teacher and data engineer. Most of the time, project acquisition 
was not a problem. We were known to a few good customers and constantly hired for projects. But the times 
have changed. 

Now I need to acquire new customers and therefor I had to expose my skills and expertise and I need references.
The latter is really a challenge, because all of my former employers or customers prefer not to be 
contacted by recruiters or others. So I can not name them as references.

To get out of this situation, I decided to create a "Skill DB", which is mainly a platform to inform 
prospective customers about my expertise and work skills, but can also be used for itself as a show 
case for my skills. I started to implement the "Skill DB" with django a few weeks ago. 

On June, 29 2021 I applied for a web project and the proposed framework was django/wagtail. I know django
but I had not been aware of wagtail until then. So I checked it out and found a precious gem. 

The customer asked me to name a reference or show me some working code, and I commited me 
to show him the actual "Skill DB" django code. 

Then I evaluated wagtail a bit more and was fascinated by this framework. So I decided to redesign my 
skill db portal and split it into two parts. A Web-Service which will be closed source and an 
"Online Profile Page" I'll publish to github as an open source project. The Open Source Project can be 
useful for other consultants (developer, tester, ...) to expose their profile to the net.
It can also be named as a show case for my development skills to prospective customers. 

And here we are. 

=== Goals

I want to develop a wagtail based CV and Profile Site for consultants. As I'm am mainly a developer, 
I'll focus on development aspects but I'll do my best to make the Site also useful for other 
kind of consultants like Tester, Architects, Designer, Data Engineers and so on. 

The following list summarizes the my initial goals:

.Project Goals
* variable types of entry pages 
** single person page (Profile Page; e.g. one developer)
** person group page (Profile Selector Page; e.g. list of the consultants of an agency)
** optional login possible, after login it's possible to use the explorer and a private chat
* navigation; a selector that is used to route pages or switch dynamic content
* menu system; one can define menus and attach them to navigations
* a generic page type used for about, contact, legal and other pages
* a set of page components to build generic pages with
** title and text block
** contact block
** additional types
* a set of page types for specific informations
** Profile/CV Page 
** Skill Listing, grouped by skill groups and work roles
** Project Listing (completed and ongoing projects)
** Explorer (can be used by registered visitors to generate custmized profiles)
** Examples (exposed coding and work examples e.g. on Github)
** Blog (proof own expertise by writing articles)
* Authentication and Authorization (Some areas can only be entered by registered users, 
  some are pulic and some need editor or administration roles)
* API to recieve documents (push service) and images

== Technical Decissions

=== Backend

.Wagtail
The backend will be realized with Wagtail. 

.Database
In development I'll stay with the preconfigured Sqlight3 database.
In production it depends on the respective user. I personally will use elasticsearch und postgres. 


=== Design

.Bootstrap
As I'm not a designer I decided to use a CSS framework (Bootstrap 5) to ease the development of the HTML templates.
In most commercial projects there are designers involved. For such a project, I prefer not use a CSS framework as, it limits the 
options to implement their requirements. 

.BEM
If the frontend implementation is based on components and supported by professional designers, I often use the BEM naming schema. 


== Structure

We will create a Wagtail installment with components that can be used on Profile Pages for consultants. 

=== The Page Types

==== Single Profile Start Page

==== Multi Profile Start Page

==== Generic Content Page

==== Project Listing Page

==== Project Detail Page

==== Reference Listing Page

==== Reference Detail Page

==== Blog Listing Page

==== Blog Post Page

=== Global Settings

=== Menus und Navigations

[appendix]
== History

[cols="1,4a"]
|===

| 2021-07-01 | 
* Initial Creation

| 2021-07-04 | 
* Motivation
* listing technical decissions (initiated)
* explaining project structures (initiated)

|===

