= Skill-DB Prototype
Peter Paul Kiefer
v1, 1. Juli 2021
:imagesdir: ./images
:icons: font
:toc: right
:toc-title: Inhalt
:toclevels: 3
:appendix-caption: Anhang
:table-caption: Tabelle
:figure-caption: Abbildung
:version-lable: Version
:source-highlighter: pygments
:stem: 

This is a description of "Skill DB"; a web portal used to expose development skills to 
prospective customers. Skill DB is a real project I plan to extend and use it 
on my own and for commercial purposes. For now I've exposed it to the public domain 
as a show case and example how I would create a web portal with django and wagtail.

== Motivation

I'm a software engineer since 1994. For more than 25 years I worked on various kinds of projects, 
with a variety of programming languages, frameworks, development techniques and tools. I worked with
different roles like developer, tester, teacher and data engineer. Most of the time, project acquisition 
was not a problem. We were known to a few good customers and constantly hired for projects. But the times 
have changed. 

Now I need to acquire new customers and therefor I had to expose my skills and expertise and I need references.
The latter is really a challenge, because all of my former employers or project customers prefer not to be 
contacted by recruiters or other prospective customers. So I can not named them as references.

To get out of this situation, I decided to create a "Skill DB", which is mainly a platform to inform 
prospective customers about my expertise and work skills, but can also be used for itself as a show 
case for my skills. I started to implement the "Skill DB" with django a few months ago. 

On June, 29 2021 I applied for a web project and the proposed framework was django/wagtail. I know django
but I was not aware of wagtail until then. So I checked it out and found a precious gem. The prospective customer 
asked me to name a reference or show me some working code, and I commited me to show him the actual "Skill DB" 
django code. But then I evaluated wagtail a bit more and was fascinated by this framework. 

I decided spontanously to reimplement the "Skill DB" with wagtail, deploy it to AWS EC2, and use it as a show case
and to expose my profile to the net. I try to achieve this in two days (a weekend), in the hope to convince the 
customer about my programming skills with HTML, CSS, Python3, Django and Wagtail.  

.Project Goals
* entry page
** optional login possible
** welcome 

* global menu (to the main pages)
* main pages
** Home (Entry Page)
** PPK Profile and CV (without the Skills and Projects)
** Skill Listing, grouped by skill groups and work roles
** Project Listing (completed and ongoing projects)
** Skill and Project Explorer (can be used by interested visitors to generate a custmized profile)
** Work Examples (exposed coding and work examples e.g. on Github)
** Blog (proof own expertise by writing articles)
* Authentication and Authorization (Some areas can only be entered by registered users, 
  some are pulic and some need editor or administration roles)
* Member pages (Workarea for registered members)
* API to recieve documents (push service) that can be downloaded from Member pages

== Technical Decissions

=== Design

As I'm not a designer I decided to use a CSS framework (Bootstrap 5) to ease the development of the HTML templates.
In most commercial projects there are designers involved. For such a project, I prefer not use a CSS framework as, it limits the 
options to implement their requirements. If the frontend implementation is based on components, I often use the 
BEM naming schema. 

[TIP]
If there is still time remaining at the end, I'll add a page where I use BEM as an example.

== Projectstructure



[appendix]
== History

[cols="1,4a"]
|===

| 2021-07-01 | 
* Initial Creation

|===

