# Generated by Django 3.2.5 on 2021-07-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210707_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='page',
            new_name='menu',
        ),
    ]
